TrajectoryPlannerROS:
  #Independent settings for the local costmap
  transform_tolerance: 0.3
  sim_time: 1.7
  sim_granularity: 0.025
  dwa: true
  vx_samples: 3
  vtheta_samples: 20
  max_vel_x: 0.20
  min_vel_x: 0.00
  max_rotational_vel: 0.40
  min_in_place_rotational_vel: 0.20
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1
  goal_distance_bias: 0.2
  path_distance_bias: 0.9
  occdist_scale: 0.01
  heading_lookahead: 0.325
  oscillation_reset_dist: 0.05
  acc_lim_th: 0.5
  acc_lim_x: 0.5
  acc_lim_y: 0.5
  heading_scoring: false
  heading_scoring_timestep: 0.8
  holonomic_robot: false
  simple_attractor: false
